version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
    groups:
      graphql-codegen:
        patterns:
          - '@graphql-codegen/*'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook*'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
