version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
    groups:
      graphql-codegen:
        patterns:
          - '@graphql-codegen/*'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
